### PR TITLE
Accessibility fix for back-to-top button

### PR DESCRIPTION
**Pull request by tqureshi-uog**
Fix accessibility issue with `Back to Top` button by adding an `aria-label` attribute for screenreaders.

### CODE REVIEW

**Comment by mmafe** [comment]
Instead of aria-label, can we use visually hidden text inside the button? See https://bootcamp.uxdesign.cc/when-to-use-aria-label-or-screen-reader-only-text-cd778627b43b and https://gomakethings.com/revisting-aria-label-versus-a-visually-hidden-class/ for more details.

**Review by mmafe — CHANGES_REQUESTED** [review]
Recommend we use a span inside the button with visibly hidden text instead of an aria-label. Also wondering if we should use "Back to top" rather than "Scroll to top" in wording.

This ⁠[article](https://www.makethingsaccessible.com/guides/visually-hiding-text/) makes a good point about the first rule of ARIA: https://www.w3.org/TR/using-aria/#firstrule "If you can use a native HTML element [HTML51] or attribute with the semantics and behavior you require already built in, instead of re-purposing an element and adding an ARIA role, state or property to make it accessible, then do so."

**Comment by mmafe** [comment]
@tqureshi-uog Example of the visually hidden version...

```
<button
  on:click={scrollToTop}
  class={twJoin(
    'flex z-10 justify-center items-center text-4xl w-16 h-16 border border-white bg-black fixed bottom-8 right-8 text-white hover:bg-uofg-red focus:bg-uofg-red transition',
    visible ? 'opacity-100' : 'opacity-0',
  )}
>
  <span aria-hidden="true"><FontAwesomeIcon icon={faChevronUp} /></span>
  <span class="sr-only">Back to top</span>
</button>
```

**Review by RazaMM — APPROVED** [review]

**Review by RazaMM — CHANGES_REQUESTED** [review]
Make sure to update the package version, but don't publish it until the branch is merged

**Review by mmafe — APPROVED** [review]
Tested on Voiceover. Works well

**Review by RazaMM — APPROVED** [review]

**Pull request merged**
